# Generated by Django 2.2.5 on 2020-05-18 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0015_auto_20200518_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_method',
            field=models.CharField(choices=[('email', 'Email'), ('github', 'Github'), ('kakao', 'Kakao')], default='email', max_length=50),
        ),
    ]
